default_platform(:ios)

platform :ios do
  desc "firebase에 배포하는 fastlane"
  lane :distribution_firebase do
    increment_build_number
    git_commit(path: "./Cproject.xcodeproj/project.pbxproj", message: "버전 올림")
    push_to_git_remote
    build_app(
      scheme: "Release",
      export_method: "app-store"
    )
    firebase_app_distribution(
        app: "1:671051319805:ios:694a4e83a27bf8f103f194",
        testers: ""
    )
  end
end
